module AguToken
  module Resources
    class Pet
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: AguToken::Category,
        ?status: AguToken::Models::PetAPI::status,
        ?tags: ::Array[AguToken::PetAPI::Tag],
        ?request_options: AguToken::request_opts
      ) -> AguToken::PetAPI

      def retrieve: (
        Integer pet_id,
        ?request_options: AguToken::request_opts
      ) -> AguToken::PetAPI

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: AguToken::Category,
        ?status: AguToken::Models::PetAPI::status,
        ?tags: ::Array[AguToken::PetAPI::Tag],
        ?request_options: AguToken::request_opts
      ) -> AguToken::PetAPI

      def delete: (
        Integer pet_id,
        ?request_options: AguToken::request_opts
      ) -> nil

      def find_by_status: (
        ?status: AguToken::Models::PetFindByStatusParams::status,
        ?request_options: AguToken::request_opts
      ) -> AguToken::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: AguToken::request_opts
      ) -> AguToken::Models::pet_find_by_tags_response

      def update_by_id: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: AguToken::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        ?additional_metadata: String,
        ?image: AguToken::Internal::file_input,
        ?request_options: AguToken::request_opts
      ) -> AguToken::Models::PetUploadImageResponse

      def initialize: (client: AguToken::Client) -> void
    end
  end
end
