module AguToken
  module Models
    module Store
      type order_delete_params =
        {  } & AguToken::Internal::Type::request_parameters

      class OrderDeleteParams < AguToken::Internal::Type::BaseModel
        extend AguToken::Internal::Type::RequestParameters::Converter
        include AguToken::Internal::Type::RequestParameters

        def initialize: (?request_options: AguToken::request_opts) -> void

        def to_hash: -> { request_options: AguToken::RequestOptions }
      end
    end
  end
end
