module AguToken
  module Models
    type pet_upload_image_params =
      { additional_metadata: String, image: AguToken::Internal::file_input }
      & AguToken::Internal::Type::request_parameters

    class PetUploadImageParams < AguToken::Internal::Type::BaseModel
      extend AguToken::Internal::Type::RequestParameters::Converter
      include AguToken::Internal::Type::RequestParameters

      attr_reader additional_metadata: String?

      def additional_metadata=: (String) -> String

      attr_reader image: AguToken::Internal::file_input?

      def image=: (
        AguToken::Internal::file_input
      ) -> AguToken::Internal::file_input

      def initialize: (
        ?additional_metadata: String,
        ?image: AguToken::Internal::file_input,
        ?request_options: AguToken::request_opts
      ) -> void

      def to_hash: -> {
        additional_metadata: String,
        image: AguToken::Internal::file_input,
        request_options: AguToken::RequestOptions
      }
    end
  end
end
