module AguToken
  module Models
    type user_logout_params =
      {  } & AguToken::Internal::Type::request_parameters

    class UserLogoutParams < AguToken::Internal::Type::BaseModel
      extend AguToken::Internal::Type::RequestParameters::Converter
      include AguToken::Internal::Type::RequestParameters

      def initialize: (?request_options: AguToken::request_opts) -> void

      def to_hash: -> { request_options: AguToken::RequestOptions }
    end
  end
end
